### ISSUE TITLE
サンプルコードの変更

### ISSUE THREAD

**Issue by tsubakimoto** [alterbooth/hol-azure-devops#6]
サンプルコードのリポジトリをこちらに変更してください。
https://github.com/alterbooth/aspnetcore-for-beginners

Azure Pipelines でのビルド対象はこちらに変更となります。
https://github.com/alterbooth/aspnetcore-for-beginners/tree/master/Final_Project/RazorPagesMovie

**Comment by hawaku** [comment]
@tsubakimoto  ## 独自のプロジェクトの作成 章の
のサンプルコードを置き換えると、ビルドが通らず、WebAppsリソース作成もできないです。

**Comment by tsubakimoto** [comment]
https://github.com/alterbooth/aspnetcore-for-beginners
はやめたので
https://github.com/alterbooth/hol-aspnetcore-sample
のままとなる。
